name: orag
description: "O-RAG: Offline RAG Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  google_fonts: ^6.1.0
  file_picker: ^8.0.0
  flutter_markdown: ^0.7.4+3
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - google_fonts/
